version: "2"

networks:
  ineuron:
    driver: bridge

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.1
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './cassandra_data:/bitnami'
    environment:
      - "CASSANDRA_CLUSTER_NAME=cassandra-cluster"
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - ineuron